<style>
    .block-amount-container {
        display: flex;
        align-items: center;
    }
    .block-amount-container > div {
        text-align: center;
        padding-left: 5px;


    }
    .block-amount-container > div > img {
        width: 100px;
        height: auto;


    }
    .block-amount-container > div.amount-description {
        width: 300px;
        height: auto;
        text-align: justify ;
    }
    .block-amount-container > div.amount-select {
        width: 100px;
    }

</style>
<?php


$amount = $block->getAmountFromConfig();
$image = $block->getImageFromConfig();
$description = $block->getDescriptionFromConfig();
$currentCurrencySymbol = $block->getCurrentCurrencySymbol();
?>
<div class="block-amount-container">
    <div>
    <img src="<?php echo $image; ?>" alt="">
    </div>
    <div class="amount-description">
        <?php echo $description?>
    </div>
    <div class="amount-select">
        <select name='donatefee' class='form-control'>
            <?php foreach($amount as $option) {
                if($option['value'] == '')
                { ?>
                    <option value="">Please select Amount</option>
                <?php } else{ ?>
                    <option value="<?php echo $option['value'] ?>"><?php print($currentCurrencySymbol)?><?php echo $option['label'] ?></option>
                <?php }} ?>
        </select>
    </div>
</div>

